### ISSUE TITLE
Idempotence issue with sites-enabled directory?

### ISSUE THREAD

**Issue by ReplicaObscura** [sbaerlocher/ansible.nginx#1]
I don't understand the purpose of these two tasks which appear right next to each other:

```
- name: creates directory sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory
  tags:
    - configuration

- name: delete directory sites-enabled
  file: path=/etc/nginx/sites-enabled/* state=absent
  tags:
    - configuration
```

It seems the first one ensures the directory exists, and the second one ensures that it's empty, however it shouldn't be empty if you're populating it with sites, so won't that cause an issue with idempotence where-by the sites are re-installed every time? Or have I misunderstood what these tasks are doing?

**Comment by sbaerlocher** [comment]
Hello bmcclure, Thanks for your feedback.

```
- name: delete directory sites-enabled
  file: path=/etc/nginx/sites-enabled/* state=absent
  tags:
    - configuration
```

The directory of the sites-enabled is re-created every time so that the pages that are no longer available in ```nginx_sites``` are no longer accessible.

If you have another suggestion to make sure the deleted pages are also removed. Can you make a pull Requst.
